version: '3.7'
services:
  db:
    build: db
    environment:
      PGDATA: /var/lib/postgresql/data/pgdata
    volumes:
      - db_pgdata:/var/lib/postgresql
      - ./scripts:/root/scripts
    ports:
      - 5432:5432
  graphql-engine:
    image: hasura/graphql-engine:latest
    ports:
      - 8080:8080
    environment:
      HASURA_GRAPHQL_DATABASE_URL: postgres://frank:frank@db:5432/layered_tables
      HASURA_GRAPHQL_ENABLE_CONSOLE: "true"
      HASURA_GRAPHQL_CONSOLE_ASSETS_DIR: /srv/console-assets
volumes:
  db_pgdata:
    name: discovery_day_q3_22_pgdata