version: '3.7'
services:
  db:
    build: db
    #image: postgis/postgis:latest
    environment:
      POSTGRES_PASSWORD: frank
      POSTGRES_USER: frank
      POSTGRES_DB: frank
      POSTGRES_HOST_AUTH_METHOD: trust
      PGDATA: /var/lib/postgresql/data/pgdata
    volumes:
      - db_pgdata:/var/lib/postgresql/data
    ports:
      - 5432:5432
  graphql-engine:
    image: hasura/graphql-engine:latest
    #image: hasura/graphql-engine:v1.3.3
    #image: hasura/graphql-engine:v1.2.1
    #image: frankinaustin/graphql-engine-arm64:v1.3.3
    container_name: visionzero_hasura
    ports:
      - 8080:8080
    environment:
      HASURA_GRAPHQL_DATABASE_URL: postgres://frank:frank@postgis:5432/atd_vz_data
      HASURA_GRAPHQL_ENABLE_CONSOLE: "true"
      HASURA_GRAPHQL_CONSOLE_ASSETS_DIR: /srv/console-assets
volumes:
  db_pgdata:
    name: discovery_day_q3_22_pgdata