import Head from "next/head";
import Image from "next/image";
import styles from "../styles/Home.module.css";
import { gql } from "@apollo/client";
import client from "../apollo-client";

export default function Home({muppets}) {
  return (
    <div className={styles.container}>
      <Head>
        <title>Muppet Status</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
        <h2 className={styles.title}>Muppet Status</h2>
        <div className={styles.grid}>
          {muppets.map((muppet) => (
            <div key={muppet.id} className={styles.card}>
              <h3>
                <a
                  href="#country-name"
                  aria-hidden="true"
                  className="aal_anchor"
                  id="country-name"
                ></a>
                {muppet.name}
              </h3>
              <p>
                Color: {muppet.color ? muppet.color.charAt(0).toUpperCase() + muppet.color.slice(1) : "Unknown"}
              </p>
              <p>Spooky: {muppet.spooky ? "✅" : "❌"}</p>
            </div>
          ))}
        </div>
      </main>

      <footer className={styles.footer}>
        <a
          href="https://vercel.com?utm_source=create-next-app&utm_medium=default-template&utm_campaign=create-next-app"
          target="_blank"
          rel="noopener noreferrer"
        >
          Powered by{" "}
          <span className={styles.logo}>
            <Image src="/vercel.svg" alt="Vercel Logo" width={72} height={16} />
          </span>
        </a>
      </footer>
    </div>
  );
}


export async function getStaticProps() {
  const { data } = await client.query({
    query: gql`
      query get_muppets {
        muppets {
          id
          color
          name
          spooky
        }
      }
    `,
      fetchPolicy: "no-cache",
  });

  return {
    props: {
      muppets: data.muppets,
    },
  };
}